name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.3
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: 6.x
      
    - name: Install dependencies
      working-directory: ./DocumentosBrasileiros
      run: dotnet restore
    
    - name: Build
      working-directory: ./DocumentosBrasileiros
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      working-directory: ./DocumentosBrasileiros/DocumentosBrasileiros.Test
      run: dotnet test --no-restore --verbosity normal
    
    - name: Generate nuget package
      working-directory: ./DocumentosBrasileiros
      if: github.ref == 'refs/heads/master'
      run: dotnet pack --configuration Release -o nupkg
      
    - name: Publish nuget package
      if: github.ref == 'refs/heads/master'
      run: find . -name *.nupkg -type f -print0 | xargs -0 -I pkg dotnet nuget push pkg -k $nuget_api_key -s "https://api.nuget.org/v3/index.json"
      env:
        nuget_api_key: ${{ secrets.NUGET_API_KEY }}
        working-directory: ./DocumentosBrasileiros/nupkg
      
